### ISSUE TITLE
FAQ: What's the correct way to shut down Pocket Core and avoid Data/WAL corruption with shutdown?

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#1102]
### PURPOSE
This issue is meant to serve as a guide to how to avoid Data/WAL corruption with shutdown.
### GUIDELINES
- If FAQ does not comprehensively cover the issue, community comments and contributions are welcome
- Although the issue is closed, FAQ issues are meant to be maintained and edited over time

## What's the correct way to shut down Pocket Core and avoid Data/WAL corruption with shutdown?
Answer the question as comprehensively as possible using bulleted lists format:
- The best way to shutdown your node is to run: `kill -SIGTERM <PID>` 

### NOTES
Anecdotal reports of shutdown corruption could signal possible shutdown issues with data corruption, especially during periods of syncing

**Comment by AusIV** [comment]
I'll note that I've observed this in our syncing process, though I had come to believe that I was not shutting down properly.

We have a periodic backup process that starts up, syncs up to current, then sends a SIGHUP to the process to start a graceful shutdown, then backs up the ~/.pocket/data folder. We recently realized that SIGHUP was not triggering a shutdown, and switched to SIGTERM and explicitly started waiting for the shutdown. We haven't encountered this since, but it also hasn't been long enough to be sure.

**Comment by andrewnguyen22** [comment]
Thanks @AusIV for the information! This is helpful

**Comment by andrewnguyen22** [comment]
Internal PNI infrastructure Dev Ops Engineers reported:
`we never experience that by resetting or providing more resources to the pocket validators` ( using proper SIGTERM )
`we have the graceful termination period for our pods`

as @AusIV indicated ^

It's possible this issue is related to improper signalling through default K8s built in solution shuttown
