### ISSUE TITLE
Allow flag for password to bypass prompt

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#1286]
**Is your feature request related to a problem? Please describe.**
```
Calling commands like pocket accounts create, requires a password prompt (difficult for deployments)

Allow a flag that can bypass the prompts by injecting the password
```

**Comment by rBurgett** [comment]
This is essential functionality that I desperately need. Production, headless applications need to be able to explicitly addresses items that otherwise would have been prompts. Prompts require prompt parsing which is extremely risky considering that wording can change and especially localization changes everything. If I don't parse the prompt and just assume the order and type of prompts, that is extremely risky as well. It is implicit, but a reliable headless application needs to be able to script explicitly. I need to be able to explicitly pass in the password or any other prompt. One example of this functionality is letsencrypt. It is made to be automated. So, if you call it directly it leads you through prompts. But, for the sake of automation every single prompt is available as a command line argument for scripting. I cannot release production-ready software to my users (in this case, node management software) if I can't properly script and automate in a reliable and explicit way.

This functionality is desperately needed! Thanks for posting the issue.
