### ISSUE TITLE
Send-Tx Timeout Unclear

### ISSUE THREAD

**Issue by DragonDmoney** [pokt-network/pocket-core#1398]
**Describe the bug**
Sometimes when you pocket query send-tx, it returns the response:
`Post "http://localhost:8081/v1/client/rawtx": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`
but it still sends the transaction.

This can be harmful because it can lead people to believe the transaction didn't go through and send again even though the transaction sends. 

In my opinion, it should either send the transaction and return the txhash and other information, or not send the transaction at all and let the user know with a more descriptive error message.

**Comment by Olshansk** [comment]
1. Did you mean `pocket accounts send-tx` instead of `pocket query send-tx`?

2. Looking at [accounts.go#L479](https://github.com/pokt-network/pocket-core/blob/staging/app/cmd/cli/accounts.go#L479), it seems like you can potentially just increase the RPC timeout in your configs or local source code. See this line (`types.SetRPCTimeout(app.GlobalConfig.PocketConfig.RPCTimeout)`) [here](https://github.com/pokt-network/pocket-core/blob/bde9c3ac20374d59e21dbf07f7c187c2f000f369/app/cmd/cli/queryUtil.go#L112).

3. In general, I do agree that the lack of atomicity can lead to error and confusion, so will look into this when time permits.

```go
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	bz, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}
```	

I think what may be happening is that the request succeeds (and is sent to the network) but reading the body of the response times out. Not a solution, but just wanted to document some preliminary thinking.

**Comment by DragonDmoney** [comment]
Yeah, I meant pocket accounts send-tx, my bad. I ended up increasing the RPC timeout. Just wanted to make this aware because it could lead to some users double-sending because they thought it didn't go through the first time.
