### ISSUE TITLE
Problem unstaking a node

### ISSUE THREAD

**Issue by anderScore-Sysop** [pokt-network/pocket-core#1451]
Hi! 
I am having problems unstaking a node. 
AppVersion: RC-0.8.2

Here is the command I run:
```
pocket nodes unstake <AdressWhereTheStakedPOKTShouldGo> <NodeAdress>  mainnet 100000 1 --pwd <PassPhraseOfNode>
2022/07/13 14:48:13 Initializing Pocket Datadir
2022/07/13 14:48:13 datadir = /root/.pocket
Enter Password: 
http://localhost:8091/v1/client/rawtx
{
    "code": 4,
    "logs": null,
    "raw_log": "{\"codespace\":\"sdk\",\"code\":4,\"message\":\"ERROR:\\nCodespace: sdk\\nCode: 4\\nMessage: \\\"signature verification failed for the transaction\\\"\\n\"}",
    "txhash": "D5F03E27419EDFE2803BEBE453CBA95A55B0721425BBE539538D0148557B6514"
}
```

I read https://github.com/pokt-network/pocket-core/issues/1172 but in the example there the unstake cmd seems to be for an older version.

**Comment by oten91** [comment]
Hi @anderScore-Sysop  the command should look like this :

` pocket nodes unstake <operatorAddr> <fromAddr> <networkID> <fee> <isBefore8.0> [flags]`

In your case and because non-custodial is not enabled your command should be :

pocket nodes unstake (NodeAdress) (NodeAdress) mainnet 10000 true --pwd <PassPhraseOfNode>

Regards

**Comment by anderScore-Sysop** [comment]
Thank you so much @oten91! 
It worked.
