### ISSUE TITLE
Infinite recursion

### ISSUE THREAD

**Issue by cristaloleg** [pokt-network/pocket-core#1578]
**Describe the bug**
I was occasionally reading your repository and had found infinite recursion.

**To Reproduce**

See `x/pocketcore/types/session.go`

```
func (s Session) HashString() string {
	return s.HashString() // <-- calls itself again
}
```

**Expected behavior**
No infinite recursion

**Screenshots**
Not applicable.

**Operating System or Platform:**
Any

**Additional context**
None.

**Comment by Olshansk** [comment]
Pretty sure we don't use this anywhere but ccing @msmania for visibility.

**Comment by msmania** [comment]
Good catch!

This function is needed for `Session` to implement `CacheStorage`, but luckily it's never called because we don't seal a cached session, which is the only place we use `CacheStorage.HashString`.  The correct return value should be `s.SessionHeader.HashString()`. Let's fix it in the next version.

**Comment by msmania** [comment]
Closing this as this was fixed.
