### ISSUE TITLE
Fix windows logs

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#51]
See logs/methods.go line 20

**Comment by iajrz** [comment]
From [the docs for `runtime.Callers`](https://golang.org/pkg/runtime/#Callers):

> To translate these PCs into symbolic information such as function names and line numbers, use CallersFrames. CallersFrames accounts for inlined functions and adjusts the return program counters into call program counters. Iterating over the returned slice of PCs directly is discouraged, as is using FuncForPC on any of the returned PCs, since these cannot account for inlining or return program counter adjustment.

Sight unseen, I _think_ some stuff gets inlined in an OS's go runtime, and not in another, and that may be causing your bug.

So the issue may be located in [line 24 of the util methods file](https://github.com/pokt-network/pocket-core/blob/29e04ad8cfcf235e89c6f439b8e512e80f93f2b2/util/methods.go#L24).

There, instead of using `FuncForPc`, I'd call `CallersFrames` on `fpcs`, invoke `Next` on the result, and get the info from the resulting  [`Frame*`](https://golang.org/pkg/runtime/#Frame).

You'll want to watch the [spot in the logging code](https://github.com/pokt-network/pocket-core/blob/29e04ad8cfcf235e89c6f439b8e512e80f93f2b2/logs/methods.go#L25) where you expect the output from `util.Callers` to be a `Func*`, but I think that's the only side effect from this change.

**Comment by andrewnguyen22** [comment]
Great suggestion! See #64 for my implementation
