### ISSUE TITLE
Challenge request for client

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#689]
Clients need to be able to challenge incorrect data by providing a proof to the network

**Comment by andrewnguyen22** [comment]
- Return block height in dispatch and relays
- Add relay request to relay response
- Accept challenge requests through RPC (within a threshold)
- Store challengeEvidence in memory
- Submit challengeClaim automatically
- Submit challengeProof automatically
- Mint for challengeProof
- Burn for challengeProof
- Store challenge receipt

**Comment by AusIV** [comment]
I'm curious how these challenges will handle legitimate variation between responses.

I come from the Ethereum ecosystem, so my example will be based on that, but I imagine there are others for other chains.

First of all, JSON keys aren't guaranteed to come in a particular order. If one client returns `{"jsonrpc:"2.0","id":"1","result":"0x"}` while another client returns `{"jsonrpc:"2.0","result":"0x","id":"1"}` the byte streams differ, but the results are semantically identical.

Then you have some method calls that have natural variability. For example the `web3_clientVersion` call differs between clients, as well as builds of clients. Obviously we wouldn't want Parity nodes to get jailed because they're running a less popular client. Another example is `eth_newFilter`, which returns a UUID for the created filter; that random element means there should never be a majority in a challenge, but if that's followed up by an `eth_getFilterChanges` all but one node will return an error that the specified filter is unknown, leaving the node for which the filter was set up subject to a challenge because their response didn't match the others.

Then there's other factors like contracts using the current block timestamp. If someone runs an ETH call on the "pending" block, the block timestamp will vary between nodes by a couple of seconds. A contract response that relies on the time would vary without the node doing anything wrong.

Then there are other methods where errors can occur somewhat randomly. As an example, in Geth an eth_call is capped at 5 seconds of execution time. Depending on the specs of the machine, a big eth_call may or may not exceed 5 seconds. Additionally, Parity has no equivalent cap. So I can imagine a scenario where a session with 3 geth nodes and 2 parity nodes where the Geth nodes time out, the Parity nodes return the correct answer, and the Parity nodes get challenged for differing with the majority.

Finally, there are other capabilities like archive data, which every node may not support. Because archive nodes are much more expensive to run, but can serve the vast majority of queries that users will run, I expect a number of operators will opt to run full nodes rather than archive nodes. If archive nodes are the majority, it may be correct to punish full nodes for failing to respond to an archival request. But if non-archive nodes are the majority, you could end up punishing the only node that correctly served the request.

I'm very curious how these issues will be addressed. I think it's important to be able to identify and punish nodes that are returning genuinely incorrect information, but there are enough RPC calls at least in Ethereum that can introduce variation that an honest actor could pretty easily be targeted with challenges.

**Comment by andrewnguyen22** [comment]
Great thoughts on the node side of the challenge transaciton
> First of all, JSON keys aren't guaranteed to come in a particular order. If one client returns {"jsonrpc:"2.0","id":"1","result":"0x"} while another client returns {"jsonrpc:"2.0","result":"0x","id":"1"} the byte streams differ, but the results are semantically identical.

This is solved by a sorted json check:
```
if JSON -> sort and compare
else -> byte comparison
```

> Then you have some method calls that have natural variability. For example the web3_clientVersion call differs between clients, as well as builds of clients. Obviously we wouldn't want Parity nodes to get jailed because they're running a less popular client. Another example is eth_newFilter, which returns a UUID for the created filter; that random element means there should never be a majority in a challenge, but if that's followed up by an eth_getFilterChanges all but one node will return an error that the specified filter is unknown, leaving the node for which the filter was set up subject to a challenge because their response didn't match the others.

> Then there are other methods where errors can occur somewhat randomly. As an example, in Geth an eth_call is capped at 5 seconds of execution time. Depending on the specs of the machine, a big eth_call may or may not exceed 5 seconds. Additionally, Parity has no equivalent cap. So I can imagine a scenario where a session with 3 geth nodes and 2 parity nodes where the Geth nodes time out, the Parity nodes return the correct answer, and the Parity nodes get challenged for differing with the majority.

> Finally, there are other capabilities like archive data, which every node may not support. Because archive nodes are much more expensive to run, but can serve the vast majority of queries that users will run, I expect a number of operators will opt to run full nodes rather than archive nodes. If archive nodes are the majority, it may be correct to punish full nodes for failing to respond to an archival request. But if non-archive nodes are the majority, you could end up punishing the only node that correctly served the request.

These are all solved with Pocket's concept of Network Identifier's:
Non-native chains are identified by hashing characteristics (archival node, geth vs parity etc.)
```
// generate the network identifier for the non native chain
func GenerateChain(ticker, netid, version, client, inter string) (string, sdk.Error) {
	return pc.NonNativeChain{
		Ticker:  ticker,
		Netid:   netid,
		Version: version,
		Client:  client,
		Inter:   inter,
	}.HashString()
}
```

> Then there's other factors like contracts using the current block timestamp. If someone runs an ETH call on the "pending" block, the block timestamp will vary between nodes by a couple of seconds. A contract response that relies on the time would vary without the node doing anything wrong.

Assuming that a majority can be reached in this case, I always say that everyone is on the same playing field. The error burns will distribute evenly due to the pseudorandom selection over time. 

And calls with consistent majority burn like `get_latest_block` is addressed in a future update
