### ISSUE TITLE
Passphrase Confirmation for Account Creation ("Re-Enter Passphrase")

### ISSUE THREAD

**Issue by armyids** [pokt-network/pocket-core#751]
When I tried to create a Pocket account, it asked me for a passphrase but unfortunately I forgot the passphrase. So, I made the second one. But Pocket didn't allow me to delete the first one or switch it to the second one because I forgot the passphrase.

The solution is just to be clear, that is the team should add 2 features.
1. Passphrase Confirmation
2. Switch Account

Hope it will be patched soon.

![unknown](https://user-images.githubusercontent.com/27644083/78405234-4665c480-762a-11ea-98c3-530420005b3e.png)

**Comment by andrewnguyen22** [comment]
I'm sorry to hear this happened to you. When you initialize your pocket core node it picks your coinbase address as the keypair to use for consensus with Tendermint config files. The only way to undo this (after losing your password) is to basically start over by deleting all contents of the data directory (or carefully manually edit all of the autogenerated config files), and import the new coinbase key into a new keybase. 

If you're requesting a feature to set the coinbase key, we are not currently implementing due to the fact that it's only useful in this exact scenario (because it would not correspond with your previously set keypair in the autogenerated config files). But If the demand presents by the community, we may revisit.
